name: Build the template

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: released

jobs:
  build:
    name: Build vue
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: mymindstorm/setup-emsdk@v11

      - uses: actions/cache@v2
        with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
        
      - name: install dependencies
        run: yarn

      - name: build project
        run: yarn build

      - name: Upload dist
        uses: actions/upload-artifact@v2
        with:
          name: dist.zip
          path: ./dist
          if-no-files-found: error