name: Build develop branch

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    name: Build vue
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: mymindstorm/setup-emsdk@v11

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: install dependencies
        run: yarn

      - name: build project
        run: yarn dev_build

      - name: Deploy to the DEV server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ env.SSH_KEY }}
          SOURCE: 'dist/'
          REMOTE_HOST: ${{ env.SERVER_IP }}
          REMOTE_USER: ${{ env.SERVER_USER }}
          TARGET: ${{ env.SERVER_DEV_PATH }}

      - name: Upload dist
        uses: actions/upload-artifact@v2
        with:
          name: dev_dist
          path: ./dist
          if-no-files-found: error