name: Build the template

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: released

jobs:
  build:
    name: Build vue
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: install emscripten
        run: brew install emscripten

      - name: install dependencies
        shell: bash
        run: yarn

      - name: build project
        shell: bash
        run: yarn build
