name: Build the template

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: released

jobs:
  build:
    name: Build vue
    runs-on: 	ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install emscripten
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          source ./emsdk_env.sh

      - name: install dependencies
        shell: bash
        run: yarn

      - name: build project
        shell: bash
        run: yarn build

      - name: Upload dist
        uses: actions/upload-artifact@v2
        with:
          name: dist.zip
          path: ./dist
          if-no-files-found: error